[XHAB-149] fixes check point alignment
KeyToTech/XHabit pull request #104
Opened 2020-02-26 13:23 UTC by phenybutum

![image](https://user-images.githubusercontent.com/44374668/75348636-e56d0300-58ab-11ea-9026-2db74aa255cf.png)

2020-02-26 14:33 UTC, vpaniush requested changes

2020-02-26 14:33 UTC, vpaniush commented on lib/src/presentation/scenes/home/home_screen.dart
> +                                : _screenSize.width * 0.02,
@phenybutum we don't need check on ScreenType here, because you pass equal values for all screen types

2020-02-26 16:30 UTC, vpaniush approved these changes

2020-02-27 07:42 UTC, bogdanustyak approved these changes

2020-02-27 07:42 UTC, merged