[XHAB-145] implements icon for visible password
KeyToTech/XHabit pull request #108
Opened 2020-02-27 21:25 UTC by phenybutum

![Screenshot_2020-02-27-23-20-31-455_com keytotech xhabits](https://user-images.githubusercontent.com/44374668/75488135-6d403380-59b8-11ea-80fe-10f3b8252d99.jpg)
![Screenshot_2020-02-27-23-20-17-510_com keytotech xhabits](https://user-images.githubusercontent.com/44374668/75488136-6dd8ca00-59b8-11ea-9a77-9505400f2144.jpg)

2020-02-27 21:34 UTC, vpaniush approved these changes

2020-03-04 17:59 UTC, bogdanustyak requested changes

2020-03-04 17:59 UTC, bogdanustyak commented on lib/src/presentation/scenes/auth/login/login_bloc.dart
> +  bool visiblePassword;
@phenybutum there is a duplication in registerBloc. Is it possible to move all visibility logic into XHPasswordTextField and maybe create a bloc class for it?

2020-03-04 21:38 UTC, vpaniush approved these changes

2020-03-05 11:57 UTC, bogdanustyak approved these changes

2020-03-05 11:57 UTC, merged