[XHAB-117] fixes notification appearence after logout
KeyToTech/XHabit pull request #80
Opened 2020-02-12 13:07 UTC by phenybutum

2020-02-13 17:55 UTC, bogdanustyak requested changes

2020-02-13 17:55 UTC, bogdanustyak commented on lib/src/presentation/scenes/home/home_screen.dart
> +      _homeScreenBloc.initPushNotificationService(context);
@phenybutum could we add this constant as a parameter into the constructor of bloc obj?

2020-02-13 18:31 UTC, phenybutum commented on lib/src/presentation/scenes/home/home_screen.dart
> +      _homeScreenBloc.initPushNotificationService(context);
@bogdanustyak we can do something like this, but in this case we are unable to make bloc obj final
![Снимок экрана (15)](https://user-images.githubusercontent.com/44374668/74466337-aa2c0680-4e9f-11ea-8c19-c68147e96d98.png)
![Снимок экрана (16)](https://user-images.githubusercontent.com/44374668/74466343-aac49d00-4e9f-11ea-9d0e-c7027a470fc9.png)

2020-02-17 07:22 UTC, bogdanustyak approved these changes

2020-02-17 07:22 UTC, merged